"""
Django settings for support_ticket_system project.

Generated by 'django-admin startproject' using Django 3.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from decouple import config
import socket

# from ticket_app.models import Priority

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



# PRIOS = ""
# DEBUG = False
# ALLOWED_HOSTS = ['.localhost', '127.0.0.1', '[::1]']
# ALLOWED_HOSTS = ['.localhost', '127.0.0.1']
# python manage.py runserver --insecure

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'login_app',
    'ticket_app',
    'django_crontab',
    'ckeditor',
    # 'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
]
hostname = socket.gethostname()

if DEBUG:
    ALLOWED_HOSTS = []

    INTERNAL_IPS = [
        '127.0.0.1',
        hostname,
    ]
    MIDDLEWARE += (
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    )
    INSTALLED_APPS += (
        'debug_toolbar',
    )

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: DEBUG,
        'INTERCEPT_REDIRECTS': False,
        'ENABLE_STACKTRACES': True,
        'IP_WHITELIST': ['127.0.0.1'],
    }

elif DEBUG == False:
    ALLOWED_HOSTS = ['.localhost', '127.0.0.1', hostname,]

ROOT_URLCONF = 'support_ticket_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            # 'builtins':[
            #     'ticket_app.template_tags'
            # ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'support_ticket_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'test',
#         'USER': 'postgres',
#         'PASSWORD': 'Liberdade17',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'US/Central'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'ticket_app/static'),
    os.path.join(BASE_DIR, 'login_app/static'),
]

# STATICFILES_DIR = [os.path.join(BASE_DIR, "static"), 
# # "ticket_app/css"
# ]



MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/login_app_static/images/'

# x = 5
# # if Priority.objects.get(toggle_auto_priorites=True):
# if x == 5:
#     print(x)
CRONJOBS = [
    # (f'{PRIOS} * * * *', 'ticket_app.cron.update_priority')
    # ('* * * * *', 'ticket_app.cron.update_priority')
    # ('0 0 * * 0', 'ticket_app.management.commands.reset_message_urls'),
    ('* * * * *', 'ticket_app.management.commands.reset_message_urls')
]
    # print("Auto-priority activated. Let's go crony.")


# CKEDITOR_CONFIGS = {
#     "default": {
#         "removePlugins": "stylesheetparser",
#         'allowedContent': True
#     }
# }


# settings.py

CKEDITOR_CONFIGS = {
    'default': {
        # 'toolbar': 'full',
        'width': '100%',
        'height': 300,
        'contentsCss': ['/static/css/custom.css'],
        'allowedContent': True,
        'toolbar': [
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['NumberedList', 'BulletedList'],
            ['Paragraph'],
            # ['Image']
            ['RemoveFormat'],
            # ['Source'],
        ],
        # 'contentsCss': ['/static/css/canned_responses.css'],

        # probably not needed 
        # 'extraAllowedContent': 'p h1 h2 h3 h4 h5 h6 pre address span b i em strike u strong',

        # 'height': '100%',
        # 'width': '100%',
        'height': 300,
        'width': 800,
        # 'allowedContent': True,
        # 'extraPlugins': 'sourcearea',
        # 'removePlugins': 'image',


        'extraPlugins': ','.join([
            'basicstyles',
            'toolbar',
            # 'image2'  ## goes with the toolbar Image
        ]),
        # 'contentsCss': ['/static/css/ticket_app.css'],
        # 'contentsLangDirection': 'ltr',
        # 'filebrowserWindowWidth': 800,
        # 'filebrowserWindowHeight': 500,
        # 'filebrowserBrowseUrl': '/browse/',
        # 'filebrowserUploadUrl': '/upload/',
        # 'filebrowserWindowFeatures': 'toolbar=0,location=0,directories=0,status=0,menubar=0,scrollbars=0,resizable=0,width=640,height=480,left=0,top=0'
    },
}


# ck edito image upload 
# pip install django-ckeditor-file-upload
# INSTALLED_APPS = [    ...    'ckeditor',    'ckeditor_file_upload',    ...]
# In CKEditor configuration settings add `'extraPlugins': 'ckeditor_file_upload',`

# CKEDITOR_UPLOAD_PATH = 'uploads/'
# CKEDITOR_IMAGE_BACKEND = 'pillow'
# CKEDITOR_RESTRICT_BY_USER = True



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

