# Generated by Django 2.2 on 2022-03-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
