# Generated by Django 2.2 on 2022-03-23 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('ticket_app', '0002_ticket_first_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_resolved_tickets', to='login_app.User'),
        ),
    ]
