# Generated by Django 2.2 on 2022-04-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_ticket_first_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='auto_priority',
            field=models.CharField(default='Low', max_length=12),
        ),
    ]
