# Generated by Django 2.2 on 2022-04-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created_at', 'priority']},
        ),
    ]
