# Generated by Django 2.2 on 2022-04-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0006_auto_20220406_0513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['auto_priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopened',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reopened_time',
            field=models.DateTimeField(null=True),
        ),
    ]
