# Generated by Django 2.2 on 2022-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0009_auto_20220410_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='cron_time',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='auto_priority',
            field=models.CharField(max_length=12),
        ),
    ]
