# Generated by Django 2.2 on 2022-04-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0010_auto_20220410_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='toggle_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
