# Generated by Django 2.2 on 2022-04-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0011_priority_toggle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='auto_priority',
            field=models.CharField(default='Low', max_length=12),
        ),
    ]
