# Generated by Django 2.2 on 2022-04-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0012_auto_20220420_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='toggle_time',
            new_name='toggle_off',
        ),
        migrations.AddField(
            model_name='priority',
            name='toggle_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
