# Generated by Django 2.2.11 on 2022-10-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0013_auto_20220422_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('condition_dependency', models.CharField(max_length=255)),
                ('condition_or', models.CharField(max_length=255)),
                ('condition_or_dependency', models.CharField(max_length=255)),
                ('condition_inclusive', models.CharField(max_length=255)),
                ('condition_inclusive_dependency', models.CharField(max_length=255)),
                ('then_action', models.CharField(max_length=255)),
                ('then_dependency', models.CharField(max_length=255)),
            ],
        ),
    ]
