# Generated by Django 2.2.11 on 2022-10-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0014_automator'),
    ]

    operations = [
        migrations.AddField(
            model_name='automator',
            name='enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
