# Generated by Django 4.1.3 on 2022-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0016_inbox_automator_then_dependency_two_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='message',
            name='trashed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
        migrations.AddField(
            model_name='message',
            name='starred',
            field=models.ManyToManyField(related_name='starred', to='ticket_app.inbox'),
        ),
        migrations.AddField(
            model_name='message',
            name='trashed',
            field=models.ManyToManyField(related_name='trashed', to='ticket_app.inbox'),
        ),
        migrations.AddField(
            model_name='message',
            name='viewed',
            field=models.ManyToManyField(related_name='viewed', to='ticket_app.inbox'),
        ),
    ]
