# Generated by Django 4.1.3 on 2022-11-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0017_remove_message_starred_remove_message_trashed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inbox',
        ),
        migrations.RemoveField(
            model_name='message',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='message',
            name='trashed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
    ]
