# Generated by Django 4.1.3 on 2022-11-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0018_remove_message_inbox_remove_message_starred_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='messages',
            field=models.ManyToManyField(related_name='inbox', to='ticket_app.message'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='starred',
            field=models.ManyToManyField(related_name='inbox_starred', to='ticket_app.message'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='trashed',
            field=models.ManyToManyField(related_name='inbox_trashed', to='ticket_app.message'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='viewed',
            field=models.ManyToManyField(related_name='inbox_viewed', to='ticket_app.message'),
        ),
    ]
