# Generated by Django 4.1.3 on 2022-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_user_full_name'),
        ('ticket_app', '0020_alter_message_options_alter_ticket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='teams', to='login_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='Unresolved', max_length=10)),
                ('priority', models.CharField(default='Low', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('archived', models.BooleanField(blank=True, default=False, null=True)),
                ('hold', models.BooleanField(blank=True, default=False, null=True)),
                ('complete', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(related_name='tasks', to='login_app.user')),
                ('tickets', models.ManyToManyField(related_name='tasks', to='ticket_app.ticket')),
            ],
        ),
    ]
