# Generated by Django 4.1.3 on 2022-12-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0021_team_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tasks',
            field=models.ManyToManyField(related_name='teams', to='ticket_app.task'),
        ),
    ]
