# Generated by Django 4.1.3 on 2023-04-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_user_id'),
        ('ticket_app', '0024_alter_ticket_options_alter_automator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='archived',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned',
            field=models.ManyToManyField(db_index=True, related_name='assigned', to='login_app.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='hold',
            field=models.CharField(blank=True, db_index=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='pinned',
            field=models.CharField(db_index=True, default='Unpinned', max_length=8),
        ),
    ]
