# Generated by Django 4.1.3 on 2023-04-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_user_id'),
        ('ticket_app', '0025_alter_ticket_archived_alter_ticket_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned',
            field=models.ManyToManyField(related_name='assigned', to='login_app.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
