# Generated by Django 4.1.3 on 2023-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0026_alter_ticket_assigned_alter_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(default='Not Set', max_length=12),
        ),
    ]
