# Generated by Django 4.1.3 on 2023-04-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0028_alter_ticket_first_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket_app.inbox'),
        ),
    ]
