# Generated by Django 4.1.3 on 2023-04-28 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0029_inbox_parent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='parent_message',
        ),
        migrations.AddField(
            model_name='message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket_app.message'),
        ),
    ]
