# Generated by Django 4.1.3 on 2023-04-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_user_failed_authorization_attempts'),
        ('ticket_app', '0030_remove_inbox_parent_message_message_parent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='parent_message',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ticket_app.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='login_app.user')),
            ],
        ),
    ]
