# Generated by Django 4.1.3 on 2023-05-04 18:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0031_remove_message_parent_message_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
