# Generated by Django 4.1.3 on 2023-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0032_alter_reply_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
