# Generated by Django 4.1.3 on 2023-05-07 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_user_failed_authorization_attempts'),
        ('ticket_app', '0033_alter_reply_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='recipients',
            field=models.ManyToManyField(related_name='received_replies', to='login_app.user'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_replies', to='login_app.user'),
        ),
    ]
