# Generated by Django 4.1.3 on 2023-05-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0034_reply_recipients_alter_reply_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannedresponse',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
