# Generated by Django 4.1.3 on 2023-05-11 21:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0035_alter_cannedresponse_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cannedresponse',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
