# Generated by Django 4.1.3 on 2023-05-23 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0036_alter_cannedresponse_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Learn',
        ),
    ]
