# Generated by Django 4.1.3 on 2023-04-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_authorization_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
